[package]
name = "rask"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
pulldown-cmark = "0.10.0"
colored = "2.1.0"
